networks:
  kx-net:
    external: true
services:
  bitfinex-quote-feed:
    image: python:3.12-slim
    container_name: bitfinex_quote_feed
    restart: always
    volumes:
      - ../feeds/bitfinex:/app
      - ../feeds/bitfinex/requirements.txt:/app/requirements.txt
      - ../logs:/app/logs
    working_dir: /app
    networks: 
      - kx-net
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python quoteFeed_bitfinex.py"
  bitfinex-trade-feed:
    image: python:3.12-slim
    container_name: bitfinex_trade_feed
    restart: always
    volumes:
      - ../feeds/bitfinex:/app
      - ../feeds/bitfinex/requirements.txt:/app/requirements.txt
      - ../logs:/app/logs
    working_dir: /app
    networks: 
      - kx-net
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python tradeFeed_bitfinex.py"
  bitmex-quote-feed:
    image: python:3.12-slim
    container_name: bitmex_quote_feed
    restart: always
    volumes:
      - ../feeds/bitmex:/app
      - ../feeds/bitmex/requirements.txt:/app/requirements.txt
      - ../logs:/app/logs
    working_dir: /app
    networks: 
      - kx-net
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python quoteFeed_bitmex.py"
  bitmex-trade-feed:
    image: python:3.12-slim
    container_name: bitmex_trade_feed
    restart: always
    volumes:
      - ../feeds/bitmex:/app
      - ../feeds/bitmex/requirements.txt:/app/requirements.txt
      - ../logs:/app/logs
    working_dir: /app
    networks: 
      - kx-net
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python tradeFeed_bitmex.py"